import type { CommunityMemberRow } from "@/lib/db";
import { PersonIcon } from "@/components/icons";

export function CommunityMembers({ members }: { members: CommunityMemberRow[] }) {
  return <section className="flex flex-col gap-4">
    <div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet">Tancerze</p><h2 className="mt-1 font-heading text-xl font-semibold text-zinc-50">Poznaj społeczność</h2><p className="mt-1 text-sm text-muted">Pokazujemy wyłącznie osoby, które świadomie włączyły widoczność profilu.</p></div><span className="text-xs text-muted">{members.length} osób</span></div>
    {members.length === 0 ? <div className="rounded-xl border border-dashed border-line p-6 text-center"><p className="text-sm text-zinc-300">Pierwsze profile tancerzy pojawią się tutaj po włączeniu widoczności.</p><a href="/konto#preferencje" className="mt-2 inline-flex text-xs font-semibold text-violet hover:text-accent">Ustaw widoczność swojego profilu →</a></div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{members.map((member) => <article key={member.id} className="rounded-xl border border-line bg-zinc-900/60 p-4"><div className="flex items-center gap-3">{member.avatarUrl ? /* eslint-disable-next-line @next/next/no-img-element -- user-provided public profile image */ <img src={member.avatarUrl} alt="" className="h-12 w-12 rounded-full object-cover" /> : member.avatarEmoji ? <span className="flex h-12 w-12 items-center justify-center rounded-full bg-violet/10 text-2xl">{member.avatarEmoji}</span> : <span className="flex h-12 w-12 items-center justify-center rounded-full bg-zinc-800 text-muted"><PersonIcon className="h-5 w-5" /></span>}<div className="min-w-0"><h3 className="truncate font-heading text-sm font-semibold text-zinc-100">{member.name}</h3><p className="text-xs text-violet">{[member.district, member.city].filter(Boolean).join(", ") || "Społeczność BachaTo"}</p></div></div>{member.bio && <p className="mt-3 line-clamp-3 text-sm leading-relaxed text-zinc-300">{member.bio}</p>}<div className="mt-3 flex gap-3 text-xs">{member.instagramUrl && <a href={member.instagramUrl} target="_blank" rel="noopener noreferrer" className="font-semibold text-accent">Instagram ↗</a>}{member.facebookUrl && <a href={member.facebookUrl} target="_blank" rel="noopener noreferrer" className="font-semibold text-accent">Facebook ↗</a>}</div></article>)}</div>}
  </section>;
}
