create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text not null,
  avatar_emoji text,
  avatar_url text,
  bio text,
  instagram_url text,
  facebook_url text,
  city text,
  district text,
  max_distance_km integer,
  preferences_json text,
  public_profile integer not null default 0,
  notification_preferences_json text,
  pref_levels text,
  pref_formats text,
  pref_days text,
  pref_time_from text,
  onboarding_survey_done_at text,
  created_at text not null
);

create table if not exists public.google_accounts (
  subject text primary key,
  user_id bigint not null unique references public.users(id) on delete cascade
);

create table if not exists public.sessions (
  id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at text not null,
  expires_at text not null
);

create table if not exists public.password_resets (
  token text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at text not null,
  expires_at text not null,
  used integer not null default 0
);

create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  item_type text not null,
  item_id text not null,
  kind text not null,
  created_at text not null,
  unique(user_id, item_type, item_id, kind)
);

create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  key text not null,
  class_id text not null,
  date_iso text not null,
  title text not null,
  instructor text,
  school text not null,
  level text,
  format text not null,
  dance_style text,
  duration_minutes integer,
  marked_at text not null,
  auto_marked integer not null default 0,
  activity_type text,
  rating integer,
  note text,
  unique(user_id, key)
);

create table if not exists public.user_activity_skips (
  user_id bigint not null references public.users(id) on delete cascade,
  key text not null,
  marked_at text not null,
  primary key(user_id, key)
);

create table if not exists public.user_event_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  event_key text not null,
  event_id integer not null,
  source text not null,
  date_iso text not null,
  title text not null,
  category text not null,
  city text,
  organizer text,
  marked_at text not null,
  unique(user_id, event_key)
);

create table if not exists public.user_event_program_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  session_key text not null,
  event_key text not null,
  event_id integer not null,
  source text not null,
  date_iso text not null,
  title text not null,
  event_title text not null,
  instructors text,
  duration_minutes integer,
  marked_at text not null,
  unique(user_id, session_key)
);

create table if not exists public.event_rsvps (
  user_id bigint not null references public.users(id) on delete cascade,
  event_key text not null,
  created_at text not null,
  primary key(user_id, event_key)
);

create table if not exists public.event_submissions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  kind text not null,
  event_key text,
  contact_email text not null,
  event_title text not null,
  event_url text,
  message text not null,
  status text not null default 'pending',
  created_at text not null
);

create table if not exists public.user_classes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  dance_style text,
  level text,
  format text not null default 'unknown',
  instructor text,
  school_name text,
  location text,
  description text,
  day_of_week integer,
  specific_date text,
  start_time text,
  end_time text,
  source_url text,
  created_at text not null
);

alter table public.users enable row level security;
alter table public.google_accounts enable row level security;
alter table public.sessions enable row level security;
alter table public.password_resets enable row level security;
alter table public.user_favorites enable row level security;
alter table public.user_activity enable row level security;
alter table public.user_activity_skips enable row level security;
alter table public.user_event_activity enable row level security;
alter table public.user_event_program_activity enable row level security;
alter table public.event_rsvps enable row level security;
alter table public.event_submissions enable row level security;
alter table public.user_classes enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
